@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

title System Context diagram for Internet Banking System

Person(customer, "Usuários", "Donos de propriedade rural, governo e empresas públicas ou privadas", $sprite="users")
System(analysis_system, "Sistema de Monitoramento do Desmatamento e Análise de Imóveis Rurais", "Permite que usuários análisem o desmatamento nas propriedades rurais")

Rel(customer, analysis_system, "Buscar informações propriedade rurais por inserção de CAR ou busca espacial e gera relatórios, usando")

SHOW_FLOATING_LEGEND()
@enduml