@startuml
skinparam actorStyle awesome
left to right direction
Usuário as User
rectangle Sistema {
usecase "UC005 - Exibir relatório" as UC05
usecase "UC006 - Imprimir relatório" as UC06
usecase "UC001 - Pesquisa sobre CAR" as UC01
usecase "UC002 - Pesquisa sobre coordenada" as UC02
usecase "UC003 - Exibir mapa" as UC03
usecase "UC004 - Ajuste de exibição do mapa" as UC04
}

:User: -- (UC01)
:User: -- (UC02)
:User: -- (UC03)
:User: -- (UC04)
:User: -- (UC05)
:User: -- (UC06)

UC01 .> UC05: <<extend>>
UC02 .> UC05: <<extend>>
UC05 .> UC06: <<extend>>
UC04 .> UC03: <<include>>
@enduml
