@startuml

enum InformationDatabaseType {
    RuralProperty
    Location
    ConservationUnit
    Deforestation
    Embargo
    QuilombolaArea
    Settlement
    UseCoverage
    Alert
}

class InformationDatabase {
    {method} +InformationDatabaseType {get; init;} : InformationDatabaseType
    {method} +DatabaseName {get; init;} : string
    {method} +LastUpdate {get; init;} : DateOnly
    {method} +IsOfficial {get; init;} : bool
    {method} -InformationDatabase()
}

interface IInformationDatabase {
    {method} +Information {get; init;} : InformationDatabase
}

@enduml
