@startuml

interface IGeoSpatialBaseIntersection extends IGeoSpatialBase {
    {method} +AreaIntersectHa {get; init;} : double
}

interface IGeoSpatialBase {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
}

interface IInformationDatabase {
    {method} +Information {get; init;} : InformationDatabase
}

class Deforestation {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +Year {get; init;} : int
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -Deforestation()
}

class Settlement {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +CodeSIPRA {get; init;} : string = ""
    {method} +NameProject {get; init;} : string = ""
    {method} +FamilyNumber {get; init;} : int
    {method} +CreationDate {get; init;} : string = ""
    {method} +WayObtaining {get; init;} : string = ""
    {method} +DateObtaining {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -Settlement()
}

class ConservationUnit{
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +UCName {get; init;} : string = ""
    {method} +Category {get; init;} : string = ""
    {method} +Group {get; init;} : string = ""
    {method} +Realm {get; init;} : string = ""
    {method} +YearCreation {get; init;} : string = ""
    {method} +ActCreation {get; init;} : string = ""
    {method} +CNUCCode {get; init;} : string = ""
    {method} +ManagingBody {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -ConservationUnit()
}

class QuilombolaArea {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +ProcessNumber {get; init;} : string = ""
    {method} +CommunityName {get; init;} : string = ""
    {method} +FamilyNumber {get; init;} : int
    {method} +DecreeDate {get; init;} : string = ""
    {method} +Realm {get; init;} : string = ""
    {method} +Phase {get; init;} : string = ""
    {method} +Responsible {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -QuilombolaArea()
}

class UseCoverage {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +Class {get; init;} : int
    {method} +Name {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -UseCoverage()
}

class Embargo {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +IdentificationEmbargoTerm {get; init;} : string = ""
    {method} +EmbargoIssuanceDate {get; init;} : DateOnly
    {method} +NameEmbargoed {get; init;} : string = ""
    {method} +CPF_CNPJ {get; init;} : string = ""
    {method} +AdministrativeProcessNumber {get; init;} : string = ""
    {method} +TotalEmbargoArea {get; init;} : string = ""
    {method} +InflationActNumber {get; init;} : string = ""
    {method} +InfractionDescription {get; init;} : string = ""
    {method} +Status {get; init;} : string = ""
    {method} +RegistrationDate {get; init;} : DateOnly
    {method} +Legislation {get; init;} : string = ""
    {method} +Article {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} -Embargo()
}

class Alert {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +AreaIntersectHa {get; init;} : double
    {method} +CodeAlert {get; init;} : int
    {method} +DetectDate {get; init;} : DateOnly
    {method} +VectorPressure {get; init;} : string = ""
    {method} +InformationDatabase {get; set;} : InformationDatabase
    {method} +Font {get; init;} : string = ""
    {method} -Alert()
}

Embargo ..up|> IGeoSpatialBaseIntersection 
Deforestation ..right|> IGeoSpatialBaseIntersection
ConservationUnit ..up|> IGeoSpatialBaseIntersection
Settlement ..|> IGeoSpatialBaseIntersection
QuilombolaArea ..left|> IGeoSpatialBaseIntersection
UseCoverage ..|> IGeoSpatialBaseIntersection
Alert ..|> IGeoSpatialBaseIntersection

Embargo ..up|> IInformationDatabase 
Deforestation ..right|> IInformationDatabase
ConservationUnit ..up|> IInformationDatabase
Settlement ..|> IInformationDatabase
QuilombolaArea ..left|> IInformationDatabase
UseCoverage ..|> IInformationDatabase
Alert ..|> IInformationDatabase

@enduml
