@startuml

interface IGeoSpatialBase {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
}

interface IGeoSpatialBaseIntersection extends IGeoSpatialBase {
    {method} +double AreaIntersectHa {get; init;}
}

class Deforestation {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +int Year {get; init;}
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} -Deforestation()
}

class Settlement implements IGeoSpatialBaseIntersection {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +string CodeSIPRA {get; init;} = ""
    {method} +string NameProject {get; init;} = ""
    {method} +int FamilyNumber {get; init;}
    {method} +string CreationDate {get; init;} = ""
    {method} +string WayObtaining {get; init;} = ""
    {method} +string DateObtaining {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    -Settlement()
}

class ConservationUnit{
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +string UCName {get; init;} = ""
    {method} +string Category {get; init;} = ""
    {method} +string Group {get; init;} = ""
    {method} +string Realm {get; init;} = ""
    {method} +string YearCreation {get; init;} = ""
    {method} +string ActCreation{get; init;} = ""
    {method} +string CNUCCode {get; init;} = ""
    {method} +string ManagingBody {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} -ConservationUnit()
}

class QuilombolaArea implements IGeoSpatialBaseIntersection{
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +string ProcessNumber {get; init;} = ""
    {method} +string CommunityName {get; init;} = ""
    {method} +int FamilyNumber {get; init;} = ""
    {method} +string DecreeDate {get; init;} = ""
    {method} +string Realm {get; init;} = ""
    {method} +string Phase {get; init;} = ""
    {method} +string Responsible {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} -QuilombolaArea()
}

class UseCoverage implements IGeoSpatialBaseIntersection{
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +int Class {get; init;}
    {method} +string Name {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} -UseCoverage()
}

class Embargo{
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +string IdentificationEmbargoTerm {get; init;} = ""
    {method} +DateOnly EmbargoIssuanceDate {get; init;}
    {method} +string NameEmbargoed {get; init;} = ""
    {method} +string CPF_CNPJ {get; init;} = ""
    {method} +string AdministrativeProcessNumber {get; init;} = ""
    {method} +string TotalEmbargoArea {get; init;} = ""
    {method} +string InflationActNumber {get; init;} = ""
    {method} +string InfractionDescription {get; init;} = ""
    {method} +string Status {get; init;} = ""
    {method} +DateOnly RegistrationDate {get; init;}
    {method} +string Legislation {get; init;} = ""
    {method} +string Article {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    -Embargo()
}

class Alert implements IGeoSpatialBaseIntersection{
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +double AreaIntersectHa {get; init;}
    {method} +int CodeAlert {get; init;}
    {method} +DateOnly DetectDate {get; init;}
    {method} +string VectorPressure {get; init;} = ""
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} +string Font {get; init;} = ""
}

Embargo ..right|> IGeoSpatialBaseIntersection 
Deforestation ..down|> IGeoSpatialBaseIntersection
ConservationUnit ..left|> IGeoSpatialBaseIntersection
@enduml
