@startuml

interface IGeoSpatialBase {
    +int Id {get; init;}
    +Geometry Geom {get; init;}
}

interface IGeoSpatialBaseIntersection extends IGeoSpatialBase {
    +double AreaIntersectHa {get; init;}
}

interface ILocationGeoSpatialBase extends IGeoSpatialBase {
    +string Code {get; init;}
    +string Name {get; init;}
}

@enduml
