@startuml

class Location implements IInformationDatabase{
    {method} +Municipality {get; init;} : Municipality
    {method} +Microregion {get; init;} : Microregion
    {method} +Messoregion {get; init;} : Messoregion
    {method} +Information {get; init;} : InformationDatabase
    {method} +Location(Municipality municipality, Microregion microregion, Messoregion messoregion)
}

interface IInformationDatabase {
    {method} +Information {get; init;} : InformationDatabase
}

interface IGeoSpatialBase {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
}

interface ILocationGeoSpatialBase extends IGeoSpatialBase {
    {method} +Code {get; init;} : string
    {method} +Name {get; init;} : string
}

class Messoregion implements ILocationGeoSpatialBase {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +Code {get; init;} : string
    {method} +Name {get; init;} : string
    {method} -Messoregion()
}

class Microregion implements ILocationGeoSpatialBase {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +Code {get; init;} : string
    {method} +Name {get; init;} : string
    {method} -Microregion()
}

class Municipality implements ILocationGeoSpatialBase {
    {method} +Id {get; init;} : int
    {method} +Geom {get; init;} : Geometry
    {method} +Code {get; init;} : string
    {method} +Name {get; init;} : string
    {method} -Municipality()
}

@enduml
