@startuml

class Location {
    {method} +Municipality Municipality
    {method} +Microregion Microregion
    {method} +Messoregion Messorerion
    {method} +Location()
    {method} +Location(Municipality municipality, Microregion microregion, Messoregion messorerion)
}

interface LocationGeoSpatialBase {
    {method} +string Code {get; init;}
    {method} +string Name {get; init;}
}

interface IGeoSpatialBase {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
}

class Messoregion {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +string Code {get; init;}
    {method} +string Name {get; init;}
    {method} -Messoregion()
}

class Microregion {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +string Code {get; init;}
    {method} +string Name {get; init;}
    {method} -Microregion()
}

class Municipality {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +string Code {get; init;}
    {method} +string Name {get; init;}
    {method} -Municipality()
}

LocationGeoSpatialBase --|> IGeoSpatialBase
Messoregion ..|> LocationGeoSpatialBase
Microregion ..|> LocationGeoSpatialBase
Municipality ..|> LocationGeoSpatialBase

@enduml
