@startuml

class RuralProperty {
    {method} +int Id {get; init;}
    {method} +Geometry Geom {get; init;}
    {method} +string ThemeName {get; init;} = ""
    {method} +string Code {get; init;} = ""
    {method} +double AreaHa {get; init;}
    {method} +string Status {get; init;} = ""
    {method} +string Type {get; init;} = ""
    {method} +string Condition {get; init;} = ""
    {method} +string Municipio {get; init;} = ""
    
    {method} +InformationDatabase InformationDatabase {get; set;}
    {method} +Location Location{get; set;}
    {method} +IList<Deforestation>? Deforestations {get; set;}
    {method} +IList<Settlement>? Settlements {get; set;}
    {method} +IList<ConservationUnit>? ConservationUnits {get; set;}
    {method} +IList<QuilombolaArea>? QuilombolaAreas {get; set;}
    {method} +IList<UseCoverage>? UsesCoverages {get; set;}
    {method} +IList<Embargo>? Embargoes {get; set;}
    {method} +IList<Alert>? Alerts {get; set;}

    {method} -RuralProperty()
}
