@startuml

class RuralProperty implements IGeoSpatialBase {
    {field} +int Id {get; init;}
    {field} +Geometry Geom {get; init;}
    {field} +string ThemeName
    {field} +string Code
    {field} +double AreaHa
    {field} +string Status
    {field} +string Type
    {field} +string Condition
    {field} +string Municipio
    {method} -RuralProperty()
}

interface IGeoSpatialBase {
    {field} +int Id {get; init;}
    {field} +Geometry Geom {get; init;}
}

@enduml
