@startuml
autonumber

"RuralPropertyService" -> "ConservationUnitService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"ConservationUnitService" --> "RuralPropertyService" : ConservationUnit

"RuralPropertyService" -> "DeforestationService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"DeforestationService" --> "RuralPropertyService" : Deforestation

"RuralPropertyService" -> "EmbargoService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"EmbargoService" --> "RuralPropertyService" : Embargo

"RuralPropertyService" -> "QuilombolaAreaService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"QuilombolaAreaService" --> "RuralPropertyService" : QuilombolaArea

"RuralPropertyService" -> "SettlementService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"SettlementService" --> "RuralPropertyService" : Settlement

"RuralPropertyService" -> "UseCoverageService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"UseCoverageService" --> "RuralPropertyService" : UseCoverage

"RuralPropertyService" -> "AlertService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"AlertService" --> "RuralPropertyService" : Alert

"RuralPropertyService" -> "IndigenouslandsService" : GetByGeometry(\n\truralProperty.Geom, \n\tcancellationToken\n)
"IndigenouslandsService" --> "RuralPropertyService" : Indigenouslands

@enduml
