@startuml
SPA -> "ReportController" : Solicita Relatório
"ReportController" -> "ReportService" : Solicita relatório
"ReportService" -> "InformationService" : Solicita as informações
database Database as Database
"InformationService" -> Database : Solicita os dados
Database --> "InformationService" : Retorna os dados
"InformationService" --> "ReportService" : Retorna as informações
"ReportService" --> "ReportService" : Gera relatório
"ReportService" --> "ReportController" : Retorna relatório 
"ReportController" --> SPA : Entrega o relatório
@enduml
