@startuml
actor Actor as Actor
Actor -> SPA : Interage com o mapa
SPA -> GeoServer : Solicita o WMS
database Database as Database
GeoServer -> Database : Solicita os dados
Database -> GeoServer : Retorna os dados
GeoServer -> GeoServer : Gera o WMS
GeoServer -> SPA : Retorna o WMS
SPA -> SPA : Renderiza o mapa
SPA -> Actor : Apresenta o mapa
@enduml
