@startuml
actor Actor as Actor
Actor -> SPA : Interage com o mapa
SPA -> GeoServer : Solicita a imagem
database Database as Database
GeoServer -> Database : Solicita os dados
Database -> GeoServer : Retorna os dados
GeoServer -> GeoServer : Gera a imagem
GeoServer -> SPA : Retorna a imagem
SPA -> SPA : Renderiza o mapa
SPA -> Actor : Apresenta o mapa
@enduml
